const contentCardsCollaborator = [
  {
    id: 1,
    idRefBranch: 1,
    photo: "./images/collaborators/image3.svg",
    nome: "Priscila Yuri",
    funcao: "Gerente",
    descricao: "Gerente de Vendas.",
    email: "priscila@sos-service.com.br",
    telephone: "011 98563-2373",
    telephoneMessage: "11985632373",
    region: "São Paulo - SP",
  },
  {
    id: 2,
    idRefBranch: 1,
    photo: "./images/collaborators/image4.svg",
    nome: "Guilherme Pukinskas",
    funcao: "Gerente",
    descricao: "Gerente de contas.",
    email: "guilherme@sos-service.com.br",
    telephone: "011 99227-2221",
    telephoneMessage: "11992272221",
    region: "São Paulo - SP",
  },
  {
    id: 3,
    idRefBranch: 1,
    photo: "./images/collaborators/image9.svg",
    nome: "Bianca Ferrari",
    funcao: "Comercial",
    descricao: "Departamento comercial.",
    email: "bid@sos-service.com.br",
    telephone: "011 99614-8863",
    telephoneMessage: "11996148863",
    region: "São Paulo - SP",
  },
  {
    id: 4,
    idRefBranch: 1,
    photo: "./images/collaborators/image6.svg",
    nome: "Nilton Cesar",
    funcao: "Engenheiro",
    descricao: "Engenheiro de Vendas.",
    email: "nilton@sos-service.com.br",
    telephone: "011 94290-3882",
    telephoneMessage: "11942903882",
    region: "São Paulo - SP",
  },
  {
    id: 5,
    idRefBranch: 1,
    photo: "./images/collaborators/image5.svg",
    nome: "Leonardo Moreira",
    funcao: "Vendedor",
    descricao: "Vendedor.",
    email: "bid@sos-service.com.br",
    telephone: "011 99230-1795",
    telephoneMessage: "11992301795",
    region: "São Paulo - SP",
  },
  {
    id: 6,
    idRefBranch: 2,
    photo: "./images/collaborators/image8.svg",
    nome: "Fernando Akira",
    funcao: "Gerente",
    descricao: "Gerente operacional.",
    email: "akira@sosservice-sul.com.br",
    telephone: "043 99806-0606",
    telephoneMessage: "43998060606",
    region: "Londrina - PR",
  },
  {
    id: 7,
    idRefBranch: 2,
    photo: "./images/collaborators/image7.svg",
    nome: "Alexandre Cavalheiro",
    funcao: "Desenvolvimento de negócio",
    descricao: "Desenvolvimento de negócios.",
    email: "cavalheiro@sosservice-sul.com.br",
    telephone: "011 96190-9001",
    telephoneMessage: "11961909001",
    region: "Londrina - PR",
  },
  {
    id: 8,
    idRefBranch: 3,
    photo: "./images/collaborators/image1.svg",
    nome: "Luiz Henrique",
    funcao: "Gerente",
    descricao: "Gerente Regional - Camaçari BA.",
    email: "vendas.camacari@sos-service.com.br",
    telephone: "071 3511-1330",
    telephoneMessage: "71997360430",
    region: "Camaçari - BA",
  },
  {
    id: 9,
    idRefBranch: 4,
    photo: "./images/collaborators/image2.svg",
    nome: "Paulo Bueno",
    funcao: "Gerente",
    descricao: "Gerente Regional – Uberlândia MG.",
    email: "vendas.uberlandia@sos-service.com.br",
    telephone: "011 97094-7869",
    telephoneMessage: "11970947869",
    region: "Ubernândia - MG",
  },
];
export { contentCardsCollaborator };
