const contentCardsCollaborator = [
  {
    id: 1,
    photo: "./images/collaborators/image1.png",
    nome: "Luiz Henrique",
    funcao: "Gerente",
    descricao: "Gerente Regional - Camaçari BA.",
    email: "vendas.camacari@sos-service.com.br",
    telephone: "071 99736-0430",
    telephoneMessage: "71997360430",
  },
  {
    id: 2,
    photo: "./images/collaborators/image2.png",
    nome: "Paulo Bueno",
    funcao: "Gerente",
    descricao: "Gerente Regional – Uberlândia MG.",
    email: "vendas.uberlandia@sos-service.com.br",
    telephone: "034 97094-7869",
    telephoneMessage: "034970947869",
  },
  {
    id: 3,
    photo: "./images/collaborators/image3.png",
    nome: "Priscila Yuri Seguiura",
    funcao: "Gerente",
    descricao: "Gerente de Vendas.",
    email: "priscila@sos-service.com.br",
    telephone: "011 98563-2373",
    telephoneMessage: "11985632373",
  },
  {
    id: 4,
    photo: "./images/collaborators/image4.png",
    nome: "Bianca Ferrari",
    funcao: "Comercial",
    descricao: "Departamento comercial.",
    email: "bid@sos-service.com.br",
    telephone: "011 99614-8863",
    telephoneMessage: "11996148863",
  },
  {
    id: 5,
    photo: "./images/collaborators/image5.png",
    nome: "Guilherme Pukinska",
    funcao: "Gerente",
    descricao: "Gerente de contas.",
    email: "guilherme@sos-service.com.br",
    telephone: "011 99227-2221",
    telephoneMessage: "011992272221",
  },
  {
    id: 6,
    photo: "./images/collaborators/image6.png",
    nome: "Leonardo Moreira",
    funcao: "Engenheiro",
    descricao: "Engenheiro de Vendas.",
    email: "bid@sos-service.com.br",
    telephone: "011 99230-1795",
    telephoneMessage: "011992301795",
  },
  {
    id: 7,
    photo: "./images/collaborators/image7.png",
    nome: "Nilton Cesar",
    funcao: "Vendedor",
    descricao: "Vendedor.",
    email: "nilton@sos-service.com.br",
    telephone: "011 94290-3882",
    telephoneMessage: "011942903882",
  },
  {
    id: 8,
    photo: "./images/collaborators/image8.png",
    nome: "Nilton Cesar",
    funcao: "Vendedor",
    descricao: "Vendedor.",
    email: "nilton@sos-service.com.br",
    telephone: "011 94290-3882",
    telephoneMessage: "011942903882",
  },
  {
    id: 9,
    photo: "./images/collaborators/image9.png",
    nome: "Nilton Cesar",
    funcao: "Vendedor",
    descricao: "Vendedor.",
    email: "nilton@sos-service.com.br",
    telephone: "011 94290-3882",
    telephoneMessage: "011942903882",
  },
];
export { contentCardsCollaborator };
