import Header from "../components/header";
import { Inter } from "next/font/google";
import "../assets/styles/globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Providers>
          <div>
            <Header />
            <div className="container mx-auto"></div>
            <div className="container">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
